//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryID { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> AssignedStaffID { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
