//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInDetail
    {
        public int StockInID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public long UnitCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StockIn StockIn { get; set; }
    }
}
